services:
  api:
    build: .
    command: sh -c "python3 run_all_migrations.py && uvicorn api:app --host 0.0.0.0 --port 9714"
    volumes:
      - ./volumes/database:/data
      - ./volumes/logs:/logs
    ports:
      - "9714:9714"
  worker:
    build: .
    command: python3 main.py
    volumes:
      - ./volumes/database:/data
      - ./volumes/logs:/logs
    environment:
      - CARBON_INTENSITY_COLLECTION_INTERVAL=60
      - HEALTH_CHECK_INTERVAL=120
      - MAIN_LOOP_INTERVAL=10
      - PYTHONUNBUFFERED=1 