services:
  api:
    build: .
    command: sh -c "python3 migrate_deduplicate_and_unique.py && uvicorn api:app --host 0.0.0.0 --port 9714"
    volumes:
      - ./volumes/database:/data
      - ./volumes/logs:/logs
    ports:
      - "9714:9714"
  worker:
    build: .
    command: python3 main.py
    volumes:
      - ./volumes/database:/data
      - ./volumes/logs:/logs 