version: '3.8'
services:
  api:
    build: .
    command: sh -c "python3 migrate_add_timestamp_sql.py && python3 migrate_deduplicate_and_unique.py && uvicorn api:app --host 0.0.0.0 --port 9714"
    volumes:
      - /opt/grid-tracker/database:/data
      - /opt/grid-tracker/logs:/logs
    ports:
      - "9714:9714"
    restart: unless-stopped
  worker:
    build: .
    command: python3 main.py
    volumes:
      - /opt/grid-tracker/database:/data
      - /opt/grid-tracker/logs:/logs
    environment:
      - CARBON_INTENSITY_COLLECTION_INTERVAL=120
      - HEALTH_CHECK_INTERVAL=1800
      - MAIN_LOOP_INTERVAL=30
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 